#!/bin/bash
desktop_dir="" # full path to "username"'s image folder instead of using PWD

while true; do
	date=$(date +%H | sed 's/\<0//g')
	if [[ "$olddate" != "$date" ]]; then
		~/bin/ksetwallpaper "$PWD/mojave_dynamic/mojave_dynamic_$date.jpeg"
	fi
	olddate=$date
done

# date=$(date +%H | sed 's/\<0//g') ; ~/bin/ksetwallpaper ~/Desktop/Mojave_Dynamic/dynamic-wall/mojave_dynamic/mojave_dynamic_$date.jpeg
