#!/bin/bash

DW_VERSION="2019.3.22"

trap "./remove -s; exit" SIGINT

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root. Enter your password...";
  sudo bash ./$0 $1;
  exit 1;
fi

usrnm=$(logname)

if ! [ -f /bin/systemctl ] && ! [[ $1 = "--cron" ]]; then
	echo -e "\e[00;31mWarning: systemd seems to be missing. Dynamic-Wall will not work. Run this setup with the --cron argument if you wish to use cron instead of systemd.\e[00m"
  exit
elif [[ $1 = "--cron" ]]; then
  method="--cron"
elif ! [[ $1 = "" ]]; then
  echo -e "\e[00;31mUnknown argument used, run either ./install or ./install --cron depending on if you want to use systemd or cron to update your wallpaper automatically\e[00m"
  exit

fi

# Set the scripts permisions

echo -e "\e[00;32m[1/5] Setting Permissions...\e[00m"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR || { echo "Error, exiting..."; exit; }
chmod a+x ./remove
chmod a+x ./lib/systemd/system-sleep/dynamicwall.sh
chmod +x ./bin/dynamic-wall/dynamicwall

# Remove previous versions

echo -e "\e[00;32m[2/5] Removing previous versions...\e[00m"
./remove -s

# Update username dependent fields

echo -e "\e[00;32m[3/5] Updating fields based on system and arguments...\e[00m"

if [[ $method = "--cron" ]]; then
  sed -i "s/scheduler=systemd/scheduler=cron/g" $DIR/bin/dynamic-wall/dynamicwall.config
  sed -i "s/scheduler=systemd/scheduler=cron/g" $DIR/bin/dynamic-wall/default.config
  sed -i "s/systemctl start dynamicwall\.service/\/bin\/bash \/home\/$usrnm\/bin\/dynamic-wall\/dynamicwall/g" $DIR/lib/systemd/system-sleep/dynamicwall.sh
  echo "Updated scheduler to cron"
else
  sed -i "s/scheduler=cron/scheduler=systemd/g" $DIR/bin/dynamic-wall/dynamicwall.config
  sed -i "s/scheduler=cron/scheduler=systemd/g" $DIR/bin/dynamic-wall/default.config
  sed -i "s/\/bin\/bash \/home\/$usrnm\/bin\/dynamic-wall\/dynamicwall/systemctl start dynamicwall.service/g" $DIR/lib/systemd/system-sleep/dynamicwall.sh
  echo "Updated scheduler to systemd"
  sed -i "s/USERNAME/$usrnm/g" $DIR/config/systemd/user/dynamicwall.service
  echo "Updated dynamicwall.service"
fi

# Start the installation

echo -e "\e[00;32m\n[4/5] Copying software files...\e[00m"
function install_files(){
    if [ "$2" = "" ];then
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d $1
      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* $1
    elif [ "$3" = "hidden" ]; then
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d /home/$2/.$1
      install -o "$usrnm" -g "$usrnm" -D $DIR/$1/* /home/$2/.$1
    elif [[ $2 = "usr" ]]; then
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d usr/$1
      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* usr/$1
    else
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d /home/$2/$1
      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* /home/$2/$1
    fi
}

install_files "/bin" "$usrnm"
install_files "/bin/dynamic-wall" "$usrnm"
cp -pR $DIR/bin/dynamic-wall/oldvar /home/"$usrnm"/bin/dynamic-wall/.oldvar
install_files "/bin/dynamic-wall/themes" "$usrnm"
install_files "/bin/dynamic-wall/themes/EarthView" "$usrnm"
install_files "/bin/dynamic-wall/themes/mojave_dynamic" "$usrnm"
install_files "/bin/dynamic-wall/themes/NewOrleans" "$usrnm"

if [[ $method = "--cron" ]]; then
  echo -e "\e[00;32m\nSkipping systemd files due to --cron installation...\e[00m"
else
  echo -e "\e[00;32m\nInstalling systemd units...\e[00m"
  install_files "config/systemd/user" "$usrnm" "hidden"
  install_files "config/systemd/user/dynamicwall.timer.d" "$usrnm" "hidden"
fi

while true; do
  echo -e "\e[00;32m\nWould you like to install a system-sleep script to trigger dynamicwall on wakeup? [y/n/?]\e[00m"
  read answer
  case $answer in
    y | Y )
      if  [[ -d /lib/systemd ]]; then
        install_files "/lib/systemd/system-sleep"
      elif [[ -d /usr/lib/systemd ]]; then
        install_files "/lib/systemd/system-sleep" usr
      else
        echo -e "\e[00;31mCan't find system-sleep directory, skipping...\e[00m"
      fi
      break
      ;;
    n | N )
      echo -e "\e[00;32m\nSkipping system-sleep files...\e[00m"
      break
      ;;
    ? )
      echo "Dynamic-Wall runs by default every 45 minutes. If the computer is suspended during this time the wallpaper will not update until another 45 minutes pass. This may lead to situations where the wallpaper stays set on a time earlier in the day meanwhile the computer suspends and wakes up later in the evening with the same wallpaper set. Installing a script in /systemd/system-sleep will trigger the Dynamic-Wall script once on wakeup solving this problem and creating a seamless experience."
      ;;
    * )
      echo -e "\e[00;31mUknown answer provided.\e[00m"
      ;;
  esac
done
# Post installation

echo -e "\e[00;32m\n[5/5] Creating software links...\e[00m"
ln -s -f /home/"$usrnm"/bin/dynamic-wall/dynamicwall /usr/local/bin/dynamicwall

if [ -f /bin/systemctl ] && ! [[ $method = "--cron" ]]; then
	echo -e "\n\033[0;33mEnabling and starting systemd...\033[0m"
    ln -s -f /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/ /etc/systemd/system/
    systemctl enable /home/"$usrnm"/.config/systemd/user/dynamicwall.service /home/"$usrnm"/.config/systemd/user/dynamicwall.timer
    systemctl start dynamicwall.timer
else
	echo -e "\n\033[0;33mCreating cronjob...\033[0m"
  crontab -u $usrnm -l | { cat; echo "*/45 * * * * /home/$usrnm/bin/dynamic-wall/dynamicwall"; } | crontab -u $usrnm -
fi

echo -e "\e[00;32m\nUpdating configuration and running dynamicwall once\e[00m"
dynamicwall -c

echo -e "\e[00;32m\nDynamic-Wall v$DW_VERSION is installed. Enjoy!\e[00m"
echo -e "\n\033[0;33m$(dynamicwall -h)\033[0m"
