#!/bin/bash

DW_VERSION="2019.3.17"

if [ $(id -u) -ne 0 ]; then
  echo "This script must be run as root. Enter your password...";
  sudo bash ./$0 $1;
  exit 1;
fi

usrnm=$(logname)

if ! [ -f /bin/systemctl ] && ! [[ $1 = "--cron" ]]; then
	echo -e "\e[00;31m Warning: systemd seems to be missing. Dynamic-Wall will not work. Run this setup with the --cron argument if you wish to use cron instead of systemd.\e[00m"
  exit
fi

if [[ $1 = "--cron" ]]; then
  method="--cron"
fi

# Set the scripts permisions

echo -e "\e[00;32m[1/5] Setting Permissions...\e[00m"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR || { echo "Error, exiting..."; exit; }
chmod a+x ./remove
chmod a+x ./lib/systemd/system-sleep/dynamicwall.sh
chmod +x ./bin/dynamic-wall/dynamic

# Remove previous versions

echo -e "\e[00;32m[2/5] Removing previous versions...\e[00m"
./remove -s

# Update username dependent fields

echo -e "\e[00;32m[3/5] Updating fields based on system and arguments...\e[00m"
sed -i "s/USERNAME/$usrnm/g" $DIR/config/systemd/user/dynamicwall.service
if [[ $method = "--cron" ]]; then
  sed -i "s/scheduler=systemd/scheduler=cron/g" $DIR/bin/dynamic-wall/dynamicwall.config
  sed -i "s/scheduler=systemd/scheduler=cron/g" $DIR/bin/dynamic-wall/default.config
fi


# Start the installation

echo -e "\e[00;32m\n[4/5] Copying the software files...\e[00m"


function install_files(){
    if [ "$2" = "" ];then
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d $1
      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* $1
    elif [ "$3" = "hidden" ]; then
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d /home/$2/.$1
      install -o "$usrnm" -g "$usrnm" -D $DIR/$1/* /home/$2/.$1
    else
      echo "installing: $1"

      install -o "$usrnm" -g "$usrnm" -d /home/$2/$1
      install -o "$usrnm" -g "$usrnm" -D $DIR$1/* /home/$2/$1
    fi
}

install_files "/bin" "$usrnm"
install_files "/bin/dynamic-wall" "$usrnm"
install_files "/bin/dynamic-wall/oldvar" "$usrnm"
cp -pR $DIR/bin/dynamic-wall/oldvar /home/"$usrnm"/bin/dynamic-wall/
install_files "/bin/dynamic-wall/themes" "$usrnm"
install_files "/bin/dynamic-wall/themes/EarthView" "$usrnm"
install_files "/bin/dynamic-wall/themes/mojave_dynamic" "$usrnm"
install_files "/bin/dynamic-wall/themes/NewOrleans" "$usrnm"

if [[ $method = "--cron" ]]; then
  echo -e "\e[00;32m\n[4/5] Skipping systemd files due to --cron installation...\e[00m"
else
  install_files "config/systemd/user" "$usrnm" "hidden"
  install_files "config/systemd/user/dynamicwall.timer.d" "$usrnm" "hidden"

  install_files "/lib/systemd/system-sleep"
fi


# Post installation

echo -e "\e[00;32m\n[5/5] Creating the software links...\e[00m"
ln -s -f /home/"$usrnm"/bin/dynamic-wall/dynamicwall /usr/local/bin/dynamicwall

if [ -f /bin/systemctl ] && ! [[ $method = "--cron" ]]; then
	echo -e "\n\033[0;33mEnabling and starting systemd...\033[0m"
    ln -s -f /home/"$usrnm"/.config/systemd/user/dynamicwall.timer.d/ /etc/systemd/system/
    systemctl enable /home/"$usrnm"/.config/systemd/user/dynamicwall.service /home/"$usrnm"/.config/systemd/user/dynamicwall.timer
    systemctl start dynamicwall.timer
else
	echo -e "\n\033[0;33mCreating cronjob...\033[0m"
  crontab -u $usrnm -l | { cat; echo "*/45 * * * * /home/$usrnm/bin/dynamic-wall/dynamicwall"; } | crontab -u $usrnm -
fi

echo -e "\e[00;32m\n Dynamic-Wall v$DW_VERSION is installed. Enjoy !\e[00m"

echo -e "\e[00;32m\n Updating configuration and running dynamic once\e[00m"
/bin/bash /home/$usrnm/bin/dynamic-wall/dynamicwall -u
