#!/bin/bash
# shellcheck source=dynamicwall.config

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root. Enter your password...";
  sudo bash ./$0;
  exit 1;
fi

usrnm=$(logname)

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR || { echo "Error, exiting..."; exit; }

eval "$(grep "theme_dir" 2>/dev/null < /home/"$usrnm"/bin/dynamic-wall/dynamicwall.config)"

if [ -f /bin/systemctl ]; then
	echo -e "\n\033[0;33mDisabling dynamicwall systemd daemons...\033[0m"
  if systemctl is-active --quiet dynamicwall.timer
  then
  systemctl stop dynamicwall.timer
  systemctl disable dynamicwall.service dynamicwall.timer
  fi
  echo ""
fi

if crontab -u "$usrnm" -l | grep "/home/$usrnm/bin/dynamic-wall/dynamicwall"; then
  echo -e "\033[0;33mRemoving cronjob...\033[0m"
  crontab -u "$usrnm" -l | grep -v "/home/$usrnm/bin/dynamic-wall/dynamicwall"  | crontab -u "$usrnm" -
fi

echo -e "\033[0;33mRemoving software links...\033[0m"
if rm /usr/local/bin/dynamicwall 2> /dev/null
then
echo "Removed symlink /usr/local/bin/dynamicwall."
fi

if [ -f /bin/systemctl ]; then
	echo -e "\n\033[0;33mRemoving dynamicwall.timer.d dropin...\033[0m"
  if rm -r /etc/systemd/system/dynamicwall.timer.d 2> /dev/null
  then
  echo "Removed /etc/systemd/system/dynamicwall.timer.d."
  fi
  echo ""
fi

echo -e "\033[0;33mRemoving software files and directories...\033[0m"

function remove_file(){
  if [ -f $1 ]; then
    if rm -f $1
    then
    echo "removed file: $1"
    fi
  fi
}

function remove_dir(){
if [[ "$2" = "ifempty" ]]; then
  if [ -d $1 ]; then
    if rm -d $1  2> /dev/null
    then
    echo "removed empty directory: $1"
    fi
  fi
else
  if [ -d $1 ]; then
    if rm -rf $1
    then
    echo "removed directory: $1"
    fi
  fi
fi
}

remove_file "/lib/systemd/system-sleep/dynamicwall.sh"
remove_file "/usr/lib/systemd/system-sleep/dynamicwall.sh"

remove_file "/home/$usrnm/.config/systemd/user/dynamicwall.timer"
remove_file "/home/$usrnm/.config/systemd/user/dynamicwall.service"
remove_file "/home/$usrnm/.config/systemd/user/dynamicwall.timer.d/2-timer.conf"

remove_dir "/home/$usrnm/.config/systemd/user/dynamicwall.timer.d"
remove_dir "/home/$usrnm/.config/systemd/user" "ifempty"
remove_dir "/home/$usrnm/.config/systemd" "ifempty"

remove_dir "$theme_dir/EarthView"
remove_dir "$theme_dir/mojave_dynamic"
remove_dir "$theme_dir/NewOrleans"
remove_dir "$theme_dir" "ifempty"

if [ "$1" = "-s" ]; then
  remove_file "/home/$usrnm/bin/dynamic-wall/default.config"
  remove_file "/home/$usrnm/bin/dynamic-wall/dynamicwall.config"
  remove_file "/home/$usrnm/bin/dynamic-wall/dynamicwall"
  remove_dir "/home/$usrnm/bin/dynamic-wall/.oldvar"
	remove_dir "/home/$usrnm/bin/dynamic-wall" "ifempty"
else
  remove_dir "/home/$usrnm/bin/dynamic-wall"
fi

remove_dir "/home/$usrnm/bin/" "ifempty"



echo ""

if [ "$1" != "-s" ]; then
	echo -e "\e[00;32mDynamic-Wall has been removed.\e[00m"
fi
