#!/bin/bash

usrnm=$(grep -i ':x:1000:' -A 0 /etc/passwd | sed 's/:x:1000:.*//')
# Source Config File
. /home/$usrnm/bin/dynamic-wall/dynamicwall.config

# Compares current refresh rate to config file and updates systemd if they dont match
active_refreshrate=$(sed -n -e 's/^.*OnBootSec=//p' /home/$usrnm/.config/systemd/user/autowall.timer)
echo "$refreshrate vs $active_refreshrate"
if [ "$refreshrate" != "$active_refreshrate" ]; then
	sed -i '/OnBootSec=/!b;cOnBootSec='$refreshrate ~/.config/systemd/user/autowall.timer.d/10-timer.conf
	sed -i '/OnUnitActiveSec=/!b;cOnUnitActiveSec='$refreshrate ~/.config/systemd/user/autowall.timer.d/10-timer.conf
	kdialog --title "Dynamic Wallpaper" --passivepopup "Configuration change detected, reloading systemd daemons" 3
	systemctl daemon-reload
fi

# Get current time
date=$(date +%H | sed 's/\<0//g')

echo "Theme currently in use is $cur_theme"
echo "Current theme directory is $theme_dir"
echo "Current ksetwallpaper directory is $kset_dir"
echo "Time is currently $date"
echo "Time offset by $timeoffset"

#Check if time has changed since last exec, then set wallpaper based on time
	if [[ "$olddate" != "$date" ]]; then
		if [[ "$date" -le "9" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 4 + $timeoffset)).jpeg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 4 + $timeoffset)).jpeg"
		elif [[ "$date" -le "16" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 5 + $timeoffset)).jpeg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 5 + $timeoffset)).jpeg"
		elif [[ "$date" -le "21" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 6 + $timeoffset)).jpeg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 6 + $timeoffset)).jpeg"
		else
			echo "exec $kset_dir $theme_dir/$cur_theme/'$cur_theme'16.jpeg"
			$kset_dir "$theme_dir/'$cur_theme'16.jpeg"
		fi
	fi
	sed -i '/olddate=/!b;colddate='$date /home/$usrnm/bin/dynamic-wall/dynamicwall.config
