#!/bin/bash

usrnm=$(grep -i ':x:1000:' -A 0 /etc/passwd | sed 's/:x:1000:.*//')
# Source Config File
. /home/$usrnm/bin/dynamic-wall/dynamicwall.config

# Compares current refresh rate to config file and updates systemd if they dont match

echo "$refreshrate vs $active_refreshrate"
if [ "$refreshrate" != "$active_refreshrate" ]; then
	sed -i '/OnBootSec='$active_refreshrate'/!b;cOnBootSec='$refreshrate /home/$usrnm/.config/systemd/user/dynamicwall.timer.d/2-timer.conf
	sed -i '/OnUnitActiveSec='$active_refreshrate'/!b;cOnUnitActiveSec='$refreshrate /home/$usrnm/.config/systemd/user/dynamicwall.timer.d/2-timer.conf
	sed -i '/active_refreshrate=/!b;cactive_refreshrate='$refreshrate /home/$usrnm/bin/dynamic-wall/dynamicwall.config
	sudo -u $usrnm \
	DISPLAY=:0 \
	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus \
	kdialog --title "Dynamic Wallpaper" --passivepopup "Configuration change detected, reloading systemd daemons" 3
	systemctl daemon-reload
fi

# Get current time
date=$(date +%H | sed 's/\<0//g')

echo "Theme currently in use is $cur_theme"
echo "Current theme directory is $theme_dir"
echo "Current ksetwallpaper directory is $kset_dir"
echo "Time is currently $date"
echo "Time offset by $timeoffset"

#Check if time has changed since last exec, then set wallpaper based on time
	if [[ "$olddate" != "$date" ]]; then
		if [[ "$date" -le "9" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 4 + $timeoffset)).jpg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 4 + $timeoffset))."jp*g
		elif [[ "$date" -le "16" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 5 + $timeoffset)).jpg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 5 + $timeoffset))."jp*g
		elif [[ "$date" -le "21" ]]; then
			echo "exec $kset_dir $theme_dir/$cur_theme/$cur_theme$(($date - 6 + $timeoffset)).jpg"
			$kset_dir "$theme_dir/$cur_theme/$cur_theme$(($date - 6 + $timeoffset))."jp*g
		else
			echo "exec $kset_dir $theme_dir/$cur_theme/'$cur_theme'16.jpeg"
			$kset_dir "$theme_dir/'$cur_theme'16."jp*g
		fi
		sed -i '/olddate=/!b;colddate='$date /home/$usrnm/bin/dynamic-wall/dynamicwall.config
	else
		echo "time hasnt changed!"
	fi
